### ISSUE TITLE
 crashes at the loading of Minecraft with the last 1.9 version of Quark and ElementsOfPowers

### ISSUE THREAD

**Issue by 0Navis0** [gigaherz/ElementsOfPower#11]
Minecraft crashes when ElementsOfPower is present in my modpack, I get a java.lang.NullPointerException. Here is the details of the error : http://pastebin.com/2uUVUn7h
It seems that the problem has already been reported, and Quark seems to be the cause of the crash, again because of this story of broken recipes and Ores Dictionnary. I posted the same issue at the Quark github https://github.com/Vazkii/Quark/issues/29

**Comment by gigaherz** [comment]
Hello, I have a "fix" (a workaround, really) for the crash already, I just haven't got around to publishing a release yet.

**Comment by gigaherz** [comment]
0.7.7 is up, and should avoid the crash.
