### ISSUE TITLE
 elementsofpower{0.7.9-alpha} crashes dedicated Forge 1.10.2 build 2006 on startup

### ISSUE THREAD

**Issue by kreezxil** [gigaherz/ElementsOfPower#15]
Issue:  elementsofpower{0.7.9-alpha} crashes dedicated Forge 1.10.2 build 2006 on startup

crash report:
https://gist.github.com/630564c388920252d2613c679b4ab5e1

fml server latest:
https://gist.github.com/2007ed0918635288c8face57a238e4bf

**Comment by gigaherz** [comment]
Hmm interesting, i missed some I18n. THis would crash on 1.9.4 and 1.10 too... on it!

**Comment by gigaherz** [comment]
/facepalm

I already fixed this -- it's just not on the release version ;P

**Comment by gigaherz** [comment]
Should be fixed in [v0.7.10](https://github.com/gigaherz/ElementsOfPower/releases/tag/v0.7.10-1.9.4). Curseforge incoming
