### ISSUE TITLE
server crash wehn trying casting basic fire spell

### ISSUE THREAD

**Issue by ZEROX7** [gigaherz/ElementsOfPower#23]
hey there wehn i want to cast a fire spell with only 1 fire essence the server crashes and btw i can try waht ever essence i want it crashes

log: https://www.dropbox.com/s/mq8p4iunfr8mt18/latest.log?dl=0

**Comment by gigaherz** [comment]
Ah yes sorry, I fixed it locally but I forgot to release an update :P
It's waiting for approval at curseforge as I write this.

**Comment by gigaherz** [comment]
And it's approved already. :P

**Comment by ZEROX7** [comment]
thx
