### ISSUE TITLE
 1.16.1-0.10.0-alpha crashes dedicated server Forge 1.16.1 build 32.0.68

### ISSUE THREAD

**Issue by kreezxil** [gigaherz/ElementsOfPower#25]
Notes:
     NoSuchMethodError caused by Forge changing the command class in build 67

crash report: 
https://gist.github.com/d0f79a2bdf65da921840315ae07057cd

fml server latest: 
https://gist.github.com/9db7fc0823c7c3c6ed0605bd780ad099

**Comment by gigaherz** [comment]
Ah yep I heard of a breaking change in the commands, I'll take a look.

**Comment by gigaherz** [comment]
0.10.1-alpha is up on curseforge.
