### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by cauliflower69** [gigaherz/ElementsOfPower#3]
Added your mod and it crashed on startup

http://pastebin.com/S0s7MgHh

**Comment by gigaherz** [comment]
Thanks for the report, I'm looking into it.

**Comment by gigaherz** [comment]
I found the location of the crash, but it surprises me that it would happen. It appears that (at least) one of the recipes in your pack creates a Shapeless Oredict recipe with an unmatched input?! My mod wrongly assumed that the list of available inputs for a recipe would always be at least 1.

I applied the same fix to the Shaped oredict recipes also, and I will be releasing a patch version in a few minutes.

**Comment by cauliflower69** [comment]
Wow! Thanks for a fast fix

**Comment by gigaherz** [comment]
Version [0.3.1alpha](https://github.com/gigaherz/ElementsOfPower/releases/tag/v0.3.1) should fix your issue. Please tell me if anything still goes wrong.

**Comment by cauliflower69** [comment]
It boots perfect now, thanks!

**Comment by gigaherz** [comment]
Happy to hear :)
