### ISSUE TITLE
1.8.9-Forge 11.15.0.1718 Crash called / by Zero

### ISSUE THREAD

**Issue by WenXin20** [gigaherz/ElementsOfPower#4]
Crash on game launch
Crash Log:
(https://github.com/gigaherz/ElementsOfPower/files/102574/crash-2016-01-24_16.13.13-client.txt)

**Comment by gigaherz** [comment]
Thanks for the report! I'll look into it right now.

**Comment by gigaherz** [comment]
I'm extremely confused. Based on my preliminary investigation, it would appear that one of the recipes in the game outputs a stack of size 0, which is causing the divide by zero exception.

I will code in a workaround for this specific case, but it makes me wonder if there is another issue that is causing the stackSize=0 situation in the first place.

**Comment by gigaherz** [comment]
This [hotfix release](https://github.com/gigaherz/ElementsOfPower/releases/tag/v0.3.2alpha) should fix your issue.

**Comment by WenXin20** [comment]
Thanks
