### ISSUE TITLE
1.8.9-Forge 11.15.1.1726 Crash

### ISSUE THREAD

**Issue by WenXin20** [gigaherz/ElementsOfPower#5]
Crash when launching game
Crash log:
(https://github.com/gigaherz/ElementsOfPower/files/118485/crash-2016-02-04_18.59.57-client.txt)

**Comment by gigaherz** [comment]
How the F... did a null get there?!

**Comment by gigaherz** [comment]
Weird, I was certain I had replied here yesterday after I published the update... Anyhow, I meant to say, I released an experimental [0.4 alpha](https://github.com/gigaherz/ElementsOfPower/releases/tag/v0.4.0-alpha), which changes a lot of the spell system and recipe scanning system, so I'd be interested in knowing if 0.4 still has the crash issue or not.

**Comment by WenXin20** [comment]
It seems to be fixed, I haven't had a crash since I updated it. :)

**Comment by gigaherz** [comment]
Nice, closing then.
