### ISSUE TITLE
1.8.9- Crash on Startup

### ISSUE THREAD

**Issue by WenXin20** [gigaherz/ElementsOfPower#6]
Crash on launch, something to do w/ the oredictionary:
http://pastebin.com/HTVHg5KY

**Comment by gigaherz** [comment]
I just uploaded [v0.4.1-alpha](https://github.com/gigaherz/ElementsOfPower/releases/tag/v0.4.1-alpha), which among other changes, may fix this issue. Feel free to recheck, but no guarantees ;P.

**Comment by WenXin20** [comment]
It seems to have fixed it, thanks. :)

**Comment by gigaherz** [comment]
Yay :)
