### ISSUE TITLE
1.8.9-Crash w/ Placemod Mod Called ArrayIndexOutOfBoundsException: 6

### ISSUE THREAD

**Issue by WenXin20** [gigaherz/ElementsOfPower#9]
forge 1777

Placemod link: 
http://minecraft.curseforge.com/projects/placemod

Crash Log:
http://pastebin.com/EwBj1xVF

**Comment by gigaherz** [comment]
The placemod appears to be trying to place a cocoon block with an invalid metadata number... I'll have to protect my getStateFromMeta methods against invalid meta values.

**Comment by gigaherz** [comment]
I just released 0.7.5, which should avoid this crash.
